// Auto-generated by build.rs
// DO NOT EDIT

//! Test discovery data generated by build script
//! Contains mappings of engine -> test_types for dynamic test discovery

pub const MYSQL_5_7: &[&str] = &["completion", "diagnostics", "hover"];
pub const MYSQL_8_0: &[&str] = &["completion"];
pub const POSTGRESQL_12: &[&str] = &["completion"];
pub const POSTGRESQL_16: &[&str] = &["completion"];
