// Copyright (c) 2025 woxQAQ
//
// Licensed under the MIT License or Apache License 2.0
// See LICENSE files for details

/**
 * Placeholder WASM bindings for SQL LSP
 *
 * This file will be replaced by wasm-pack generated output
 * once the WASM build is configured.
 *
 * Generated by: wasm-pack
 * Target: web
 */

export * from './unified_sql_lsp_lsp_bg.js';
