/* tslint:disable */
/* eslint-disable */
/**
* Generated by wasm-pack
*
* NOTE: This is a placeholder file.
* The actual WASM module will be generated when wasm-pack build runs successfully.
*
* Current status: Build fails due to known WASM compatibility issues:
* - mio crate doesn't support wasm32-unknown-unknown target
* - getrandom crate requires "js" feature for WASM
*
* This is expected and documented in the implementation plan.
*/

export * from './unified_sql_lsp_lsp_bg.js';

// Stub LspServer class for playground development
export class LspServer {
  constructor(dialect) {
    console.log(`LspServer stub initialized with dialect: ${dialect}`);
  }
}

export async function init() {
  console.log('WASM init stub called');
  return;
}

export default {
  init,
  LspServer
};
